# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies (including dev for build)
RUN npm install

# Copy rest of the files
COPY . .

# Build the project
RUN npm run build

# Remove dev dependencies
RUN npm prune --production

# Expose stdio by default, no ports

# Command to run the MCP server
CMD ["node", "dist/index.js"]
