export type TradeRouterKeys =
  | "GET_SUPPORTED_CHAIN"
  | "GET_TOKENS"
  | "GET_LIQUIDITY_SOURCES"
  | "APPROVE_TRANSACTIONS"
  | "GET_QUOTES"
  | "GET_SWAP_INSTRUCTIONS"
  | "EXECUTE_SWAP"
  | "GET_TRANSACTION_STATUS";

export type GatewayRouterKeys =
  | "GET_SUPPORTED_CHAIN"
  | "GET_GAS_PRICE"
  | "GET_GAS_LIMIT"
  | "SIMULATE_TRANSACTIONS"
  | "BRODCAST_TRANSACTIONS"
  | "GET_TRANSACTION_ORDER";

export type MarketPriceRouterKeys =
  | "GET_SUPPORTED_CHAIN"
  | "GET_PRICE"
  | "GET_BATCH_TOKEN_PRICE"
  | "GET_TRADES"
  | "GET_CANDLESTICKS"
  | "GET_CANDLESTICKS_HISTORY";

export type IndexPriceRouterKeys =
  | "GET_SUPPORTED_CHAIN"
  | "GET_TOKEN_INDEX_PRICE"
  | "GET_HISTORICAL_INDEX_PRICE";

export type BalanceRouterKeys =
  | "GET_SUPPORTED_CHAIN"
  | "GET_TOTAL_VALUE"
  | "GET_TOTAL_TOKEN_BALANCES"
  | "GET_SPECIFIC_TOKEN_BALANCE";

export type TransactionRouterKeys =
  | "GET_SUPPORTED_CHAIN"
  | "GET_HISTORY_BY_ADDRESS"
  | "GET_SPECIFIC_TRANSACTION";
